simple:
  model: gpt-4.1-mini
  temperature: 0.5
  top_p: 0.5
  n: 1
  max_tokens: 3000
  price:
    input: 0.4
    output: 1.6

simple_json:
  model: gpt-4.1-mini
  temperature: 0.5
  top_p: 0.5
  n: 1
  max_tokens: 3000
  json: true
  price:
    input: 0.4
    output: 1.6

primary_agent:
  model: gpt-5
  n: 1
  max_tokens: 4000
  reasoning:
    effort: low
  price:
    input: 1.25
    output: 10.0

assistant:
  model: gpt-5
  n: 1
  max_tokens: 6000
  reasoning:
    effort: medium
  price:
    input: 1.25
    output: 10.0

generator:
  model: gpt-5.2
  n: 1
  max_tokens: 8192
  reasoning:
    effort: medium
  price:
    input: 1.75
    output: 14.0

refiner:
  model: gpt-5
  n: 1
  max_tokens: 16384
  reasoning:
    effort: high
  price:
    input: 1.25
    output: 10.0

adviser:
  model: gpt-5.2
  n: 1
  max_tokens: 4000
  reasoning:
    effort: low
  price:
    input: 1.75
    output: 14.0

reflector:
  model: o4-mini
  n: 1
  max_tokens: 3000
  reasoning:
    effort: medium
  price:
    input: 1.1
    output: 4.4

searcher:
  model: gpt-4.1-mini
  temperature: 0.7
  top_p: 0.8
  n: 1
  max_tokens: 4000
  price:
    input: 0.4
    output: 1.6

enricher:
  model: gpt-4.1-mini
  temperature: 0.7
  top_p: 0.8
  n: 1
  max_tokens: 4000
  price:
    input: 0.4
    output: 1.6

coder:
  model: gpt-5.2
  n: 1
  max_tokens: 6000
  reasoning:
    effort: medium
  price:
    input: 1.75
    output: 14.0

installer:
  model: o4-mini
  n: 1
  max_tokens: 6000
  reasoning:
    effort: low
  price:
    input: 1.1
    output: 4.4

pentester:
  model: o4-mini
  n: 1
  max_tokens: 4000
  reasoning:
    effort: low
  price:
    input: 1.1
    output: 4.4