simple:
  model: gpt-4.1-mini
  temperature: 0.5
  top_p: 0.5
  n: 1
  max_tokens: 4000
  price:
    input: 0.4
    output: 1.6
    cache_read: 0.1

simple_json:
  model: gpt-4.1-mini
  temperature: 0.5
  top_p: 0.5
  n: 1
  max_tokens: 4000
  json: true
  price:
    input: 0.4
    output: 1.6
    cache_read: 0.1

primary_agent:
  model: o4-mini
  n: 1
  max_tokens: 6000
  reasoning:
    effort: medium
  price:
    input: 1.1
    output: 4.4
    cache_read: 0.275

assistant:
  model: o4-mini
  n: 1
  max_tokens: 6000
  reasoning:
    effort: medium
  price:
    input: 1.1
    output: 4.4
    cache_read: 0.275

generator:
  model: o3
  n: 1
  max_tokens: 8192
  reasoning:
    effort: medium
  price:
    input: 2.0
    output: 8.0
    cache_read: 0.5

refiner:
  model: o3
  n: 1
  max_tokens: 8192
  reasoning:
    effort: high
  price:
    input: 2.0
    output: 8.0
    cache_read: 0.5

adviser:
  model: gpt-5.2
  n: 1
  max_tokens: 6000
  reasoning:
    effort: low
  price:
    input: 1.75
    output: 14.0
    cache_read: 0.175

reflector:
  model: o4-mini
  n: 1
  max_tokens: 4000
  reasoning:
    effort: medium
  price:
    input: 1.1
    output: 4.4
    cache_read: 0.275

searcher:
  model: gpt-4.1-mini
  temperature: 0.7
  top_p: 0.8
  n: 1
  max_tokens: 4000
  price:
    input: 0.4
    output: 1.6
    cache_read: 0.1

enricher:
  model: gpt-4.1-mini
  temperature: 0.7
  top_p: 0.8
  n: 1
  max_tokens: 4000
  price:
    input: 0.4
    output: 1.6
    cache_read: 0.1

coder:
  model: o3
  n: 1
  max_tokens: 16384
  reasoning:
    effort: low
  price:
    input: 2.0
    output: 8.0
    cache_read: 0.5

installer:
  model: o4-mini
  n: 1
  max_tokens: 8192
  reasoning:
    effort: low
  price:
    input: 1.1
    output: 4.4
    cache_read: 0.275

pentester:
  model: o4-mini
  n: 1
  max_tokens: 8192
  reasoning:
    effort: low
  price:
    input: 1.1
    output: 4.4
    cache_read: 0.275
